server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot-jpa
    username: root
    password: Jovaunn1
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#      dialect: org.hibernate.dialect.MySQL5InnoDBDialect   支持事务